// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwdqihtazjxsbhqmehxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZHFpaHRhemp4c2JocW1laHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODAyMDEsImV4cCI6MjA2NTY1NjIwMX0.K4tAhP1GLwlPxzNmn1F6so8z-GxbE7gpc1M60X1u-cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);